=== ines-web/cv24v1/src/main/resources/cv24.tp1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://univ.fr/cv24" xmlns="http://univ.fr/cv24"
    elementFormDefault="unqualified" >
    
    <!-- les contrainte   -->
  <xs:simpleType name="texte">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>


  <xs:simpleType name="String32maj">
    <xs:restriction base="texte">
      <xs:pattern value="[\p{Lu}\s'\-]{1,32}"/>
      <xs:maxLength value="32"/>
    </xs:restriction>
  </xs:simpleType>

    
  <xs:simpleType name="String32">
<xs:restriction base="xs:string">
<xs:maxLength value="32"/>
<xs:pattern value="[\p{L}\s'\-]{1,32}"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="String128">
<xs:restriction base="xs:string" >
<xs:maxLength value="128"/>
<xs:pattern value="[\p{L}\p{Nd}\s.,:;'@()-=_*~$?!#&amp;]{1,128}"></xs:pattern>
</xs:restriction>
</xs:simpleType>
 
  <xs:simpleType name="tel">
    <xs:restriction base="texte">
    	 <xs:pattern value="(\d{10})|(\d{2}\s\d{2}\s\d{2}\s\d{2}\s\d{2})|(\d\s\d{3}\s\d{3}\s\d{3})|(\+33\s\d\s\d{2}\s\d{2}\s\d{2}\s\d{2})"/>
    </xs:restriction>
  </xs:simpleType>
  
<xs:simpleType name="emailtype">
    <xs:restriction base="xs:string">
         <xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.[a-zA-z]{2,3}"/>
    </xs:restriction>
</xs:simpleType>

  
   <xs:simpleType name="genreType">
    <xs:restriction base="texte">
      <xs:enumeration value="M."/>
      <xs:enumeration value="Mme"/>
      <xs:enumeration value="Mrs"/>
      <xs:enumeration value="Miss"/>
      <xs:enumeration value="Mr"/>
    </xs:restriction>
  </xs:simpleType> 
  
 <xs:element name="cv24" type="cv24" ></xs:element>
 <xs:element name="identite" type="identiteType"></xs:element>
 <xs:element name="objectif" type="objectifType"></xs:element>
 <xs:element name="prof" type="profType" ></xs:element>
 <xs:element name="competences" type="competencesType" ></xs:element>
 <xs:element name="divers" type="diversType" ></xs:element>
<xs:complexType name="cv24">
	<xs:all>
		<xs:element ref="identite" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element ref="objectif" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element ref="prof" minOccurs="0" maxOccurs="1"></xs:element>
		<xs:element ref="competences" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element ref="divers" minOccurs="0" maxOccurs="1"></xs:element>
	</xs:all>
</xs:complexType>


<xs:complexType name="identiteType">
	<xs:sequence>
		<xs:element name="genre" type="genreType" minOccurs="1" maxOccurs="1"> </xs:element>
		<xs:element name="nom" type="String32maj" minOccurs="1" maxOccurs="1"> </xs:element>
		<xs:element name="prenom" type="String32" minOccurs="1" maxOccurs="1"> </xs:element>
		<xs:element name="tel" type="tel" minOccurs="0" maxOccurs="1"> </xs:element>
		<xs:element name="mel" type="emailtype" minOccurs="0" maxOccurs="1"> </xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="objectifType">
        <xs:sequence>
            <xs:element name="objectif" type="String128" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
	  <xs:attribute name="status"  use="required">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="stage" />
        <xs:enumeration value="emploi" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
</xs:complexType>

<xs:complexType name="profType">
	<xs:sequence>
		<xs:element name="detail" type="detailType" minOccurs="1" maxOccurs="unbounded"> </xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="detailType">
	<xs:sequence>
		  <xs:element name="datedeb" type="xs:date" minOccurs="1" maxOccurs="1"/>
	      <xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"/>
	      <xs:element name="titre" type="String128" minOccurs="1" maxOccurs="1"/>    
	</xs:sequence>
</xs:complexType>

<xs:complexType name="certifType">
	<xs:sequence>
		  <xs:element name="datedeb" type="xs:date" minOccurs="1" maxOccurs="1"/>
	      <xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"/>
	      <xs:element name="titre" type="String32" minOccurs="1" maxOccurs="1"/>    
	</xs:sequence>
</xs:complexType>
<xs:complexType name="competencesType">
		<xs:sequence>
		<xs:element name="diplÃ´me" type="diplometype" minOccurs="1" maxOccurs="5"> </xs:element>
		<xs:element name="certif" type="certifType" minOccurs="0" maxOccurs="unbounded"> </xs:element>
	</xs:sequence>
	

</xs:complexType>
<xs:complexType name="diplometype">
  <xs:sequence> 
  		<xs:sequence>
	 		<xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1"/>
	      	<xs:element name="institut" type="String32" minOccurs="0" maxOccurs="1"/>
	      	<xs:element name="titre" type="String32" minOccurs="1" maxOccurs="5"/>
		</xs:sequence>
  </xs:sequence>
			<xs:attribute name="niveau" type="niveauType" use="required">

			</xs:attribute>
</xs:complexType>

 <xs:simpleType name="niveauType">
    	<xs:restriction base="xs:int">
    		<xs:minInclusive value="1" />
    		<xs:maxInclusive value="8" />
    	</xs:restriction>
  
 </xs:simpleType>



<xs:complexType name="diversType">
		<xs:sequence>
	 		<xs:element name="lv" type="lvLangType"  minOccurs="1" maxOccurs="5"/>
	      	<xs:element name="autre" type="autreType" minOccurs="0" maxOccurs="3"/>      	
		</xs:sequence>	
</xs:complexType>

  <xs:complexType name="lvLangType">
  
      <xs:attribute name="lang" type="xs:string" use="required" > </xs:attribute>
      <xs:attribute name="nivs" type ="nivType" use="optional" >  </xs:attribute>     
      <xs:attribute name="cert" type="certifiType" use="required" > </xs:attribute>
 	  <xs:attribute name="nivi"  type ="niviType" use="optional" > </xs:attribute>      
</xs:complexType>

  <xs:complexType name="autreType">
      <xs:attribute name="titre" type="String32" use="required"  />
      <xs:attribute name="comment" type="String128" use="optional"/>
  </xs:complexType>

   <xs:simpleType name="niviType">
	    	<xs:restriction base="xs:int">
	    		<xs:minInclusive value="10" />
	    		<xs:maxInclusive value="990" />
	    	</xs:restriction>
	    </xs:simpleType>




<xs:simpleType name="certifiType">

	<xs:restriction base="xs:string">
	<xs:enumeration value="MAT"></xs:enumeration>
	<xs:enumeration value="CLES"></xs:enumeration>
	<xs:enumeration value="TOEIC"></xs:enumeration>
	</xs:restriction>
</xs:simpleType>

 

<xs:simpleType name="nivType">

	<xs:restriction base="xs:string">	
		<xs:enumeration value="A1"></xs:enumeration>	
		<xs:enumeration value="A2"></xs:enumeration>	
		<xs:enumeration value="B1"></xs:enumeration>		
		<xs:enumeration value="B2"></xs:enumeration>	
		<xs:enumeration value="C1"></xs:enumeration>
	</xs:restriction>

</xs:simpleType>

 



  
  
  
	    
	   

</xs:schema>

=== ines-web/cv24v1/src/main/resources/cv24.test.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd ">
  <cv24:identite>
    <genre>M.</genre>
    <nom>N</nom>
    <prenom>prenom</prenom>
    <tel>+33 1 23 45 67 89</tel>
    <mel>mel@hs.fr</mel>
  </cv24:identite>
  <cv24:objectif status="stage">
  <objectif>test
  </objectif>
  </cv24:objectif>
  <cv24:prof>
    <detail>
      <datedeb>2001-01-01</datedeb>
      <datefin>2001-01-01</datefin>
      <titre>titre</titre>
    </detail>
    
  </cv24:prof>
  <cv24:competences>
    <diplÃ´me niveau="1">
      <date>2001-01-01</date>
      <institut>institut</institut>
      <titre>titre</titre>

      
    </diplÃ´me>
    
    
    <certif>
      <datedeb>2001-01-01</datedeb>
      <datefin>2001-01-01</datefin>
      <titre>titre</titre>
      
    </certif>
    
    
    
  </cv24:competences>
  
  <cv24:divers>
    <lv cert="MAT" lang="fr"/>
    
    <autre titre="ss" comment="tets"/>
  </cv24:divers>
</cv24:cv24>

=== ines-web/cv24v1/src/main/resources/cv24.test.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd">
    <cv24:identite>
		<genre>M.</genre>
        <nom>RAYANE</nom>
        <prenom>Rayane</prenom>
        <tel>0345678901</tel>
        <mel>rayane@example.com</mel>
    </cv24:identite>
    <cv24:objectif status="emploi">
      <objectif>Journaliste multimedia specialise dans les affaires internationales</objectif>

    </cv24:objectif>
    <cv24:prof>
       <detail>
            <datedeb>2013-07-01</datedeb>
            <datefin>2021-07-01</datefin>
            <titre>Redacteur en chef</titre>
        </detail>
    </cv24:prof>
    <cv24:competences>
        <diplôme niveau="6">
        <date>2013-06-15</date>
            <institut>Ecole de Journalisme de Paris</institut>
            <titre>Master en Journalisme</titre>
        </diplôme>
        <certif>
             <datedeb>2015-10-01</datedeb>
            <titre>Certification en Journalisme </titre>
        </certif>
    </cv24:competences>
    <cv24:divers>
      <lv lang="Français" nivs="C1" cert="MAT" nivi="900"/>
        <autre titre="Photographie" comment="Expositions photographiques sur les cultures du monde"/>
  </cv24:divers>
</cv24:cv24>

=== ines-web/cv24v1/src/main/resources/cv24Minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd">
      <cv24:identite>
        <genre>Miss</genre>
        <nom>KHICHA</nom>
        <prenom>Ines</prenom>
        <tel>07 68 74 15 95</tel>
    </cv24:identite>
    <cv24:objectif status="stage">
        <objectif>ABCDefé&amp;@;:;$#*</objectif>
    </cv24:objectif>
    <cv24:competences>
        <diplôme niveau="3">
            <date>2021-12-12</date>
            <titre>LicenceséàL</titre>
        </diplôme>
    </cv24:competences>
</cv24:cv24>

=== ines-web/cv24v1/src/main/resources/cv24 Complet .xml
<?xml version="1.0" encoding="UTF-8"?>
<cv24:cv24 xmlns:cv24="http://univ.fr/cv24" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv24 cv24.tp1.xsd">
    <cv24:identite>
        <genre>Miss</genre>
        <nom>TIRECHE</nom>
        <prenom>Amira</prenom>
        <tel>0987654321</tel>
        <mel>ammira.tirreche@example.com</mel>
    </cv24:identite>
    <cv24:objectif status="stage">
        <objectif>Etudiante en Master de Génie logiciel cherchant un stage d'été</objectif>
    </cv24:objectif>
    <cv24:prof>
        <detail>
            <datedeb>2021-06-01</datedeb>
            <datefin>2021-08-31</datefin>
            <titre>Stagiaire en développement internationales</titre>
        </detail>
    </cv24:prof>
    <cv24:competences>
        <diplôme niveau="5">
            <date>2021-09-01</date>
            <institut>Faculte d'informatique de Paris</institut>
            <titre>Master en Informatique</titre>
        </diplôme>
            <certif>
            <datedeb>2019-05-01</datedeb>
            <titre>Certification en DevOps </titre>
        </certif>
    </cv24:competences>
    <cv24:divers>
        <lv lang="Espagnol" nivs="A2" cert="TOEIC" />
        <autre titre="Benevolat" comment="Participation a des projets humanitaires en Amerique Latine"/>
    </cv24:divers>
</cv24:cv24>
